environments:
  production:
    values:
      - ../config/nodes.yaml
  local:
    values:
      - ../config/nodes.yaml
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  - name: kube-prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 34.6.0
    values:
      - ./config/kube-prometheus-stack-values.yaml.gotmpl
