environments:
  production:

repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx

releases:
- name: nginx-ingress
  chart: ingress-nginx/ingress-nginx
  version: 4.0.18
  values:
  - ./config/nginx-ingress-values.yaml.gotmpl
