environments:
  production:
  local:

repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: grafana
  chart: grafana/grafana
  version: 6.14.2
  values:
  - ./config/grafana-values.yaml.gotmpl
