environments:
  production:
  local:

repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

releases:
- name: loki
  chart: grafana/loki
  version: 2.8.1
  namespace: monitoring
  values:
    - ./config/loki-values.yaml.gotmpl
- name: promtail
  chart: grafana/promtail
  version: 3.9.1
  namespace: monitoring
  values:
    - ./config/promtail-values.yaml.gotmpl

