environments:
  production:
  local:
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
releases:
  - name: loki
    chart: grafana/loki
    version: 2.10.3
    namespace: monitoring
    values:
      - ./config/loki-values.yaml.gotmpl
  - name: promtail
    chart: grafana/promtail
    version: 2.10.3
    namespace: monitoring
    values:
      - ./config/promtail-values.yaml.gotmpl
