environments:
  production:
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: external-dns
    chart: bitnami/external-dns
    namespace: default
    version: 6.2.4
    values:
      - ./config/external-dns-values.yaml.gotmpl
