environments:
  production:
  local:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:
- name: matrixbot
  namespace: monitoring
  chart: w3f/matrixbot
  version: v1.3.2
  values:
  - ./config/matrixbot-values.yaml.gotmpl

- name: kusama-validator-watcher-matrixbot
  namespace: kusama
  chart: w3f/matrixbot
  version: v1.3.2
  values:
  - ./config/matrixbot-values.yaml.gotmpl  
  - ./config/kusama/validator-matrixbot-values.yaml.gotmpl

- name: polkadot-validator-watcher-matrixbot
  namespace: polkadot
  chart: w3f/matrixbot
  version: v1.3.2
  values:
  - ./config/matrixbot-values.yaml.gotmpl  
  - ./config/polkadot/validator-matrixbot-values.yaml.gotmpl
