environments:
  production:
    values:
    - ../config/nodes.yaml
  local:
    values:
    - ../config/nodes.yaml

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:

- name: kusama-validator-watcher
  namespace: kusama
  chart: w3f/polkadot-watcher
  version: v3.1.3
  values:
  - ./config/watcher.yaml.gotmpl
  - ./config/kusama/validator-watcher-values.yaml.gotmpl

- name: polkadot-validator-watcher
  namespace: polkadot
  chart: w3f/polkadot-watcher
  version: v3.1.3
  values:
  - ./config/watcher.yaml.gotmpl
  - ./config/polkadot/validator-watcher-values.yaml.gotmpl
