environments:
  production:
    values:
      - ../config/validators.yaml
  local:
    values:
      - ../config/validators.yaml
repositories:
  - name: w3f
    url: https://w3f.github.io/helm-charts/
releases:
  - name: kusama-payouts-claimer
    chart: w3f/polkadot-k8s-payouts
    namespace: kusama
    version: v0.1.19
    values:
      - ./config/claimer.yaml.gotmpl
      - ./config/kusama/claimer.yaml.gotmpl
  - name: polkadot-payouts-claimer
    chart: w3f/polkadot-k8s-payouts
    namespace: polkadot
    version: v0.1.19
    values:
      - ./config/claimer.yaml.gotmpl
      - ./config/polkadot/claimer.yaml.gotmpl
