environments:
  production:
  local:

repositories:
  - name: w3f
    url: https://w3f.github.io/helm-charts/

releases: 
  - name: substrate-alertrules
    namespace: monitoring
    chart: w3f/substrate-alertrules
    version: ^v0.1.4
    values:
    - ./config/substrate-alertrules-values.yaml.gotmpl    