environments:
  production:

repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager  # https://cert-manager.io/docs/installation/kubernetes/#installing-with-helm
  version: v1.7.1
  values:
  - ./config/cert-manager-values.yaml.gotmpl
